# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""
Real-to-complex FFT (rfft) implementation using Triton.

This implements a basic DFT-based rfft.
For production use, one would implement a proper FFT algorithm.
"""
import logging

import math
import torch
import triton
import triton.language as tl

from flag_gems.utils.triton_lang_extension import use_tl_extra

logger = logging.getLogger(__name__)


def _fft_r2c_1d_triton(input_tensor, dim, normalization, onesided):
    """1D real-to-complex FFT using Triton kernel.

    Uses a vectorized approach where each thread block processes
    multiple output elements.
    """
    n = input_tensor.shape[dim]

    # For now, only support power-of-2 sizes for simplicity
    if n & (n - 1) != 0:
        raise ValueError(f"Currently only power-of-2 sizes supported, got {n}")

    # Ensure contiguous
    input_tensor = input_tensor.contiguous()

    # Compute output size
    if onesided:
        output_size = n // 2 + 1
    else:
        output_size = n

    # Build output shape
    output_shape = list(input_tensor.shape)
    output_shape[dim] = output_size

    # Create output tensors
    output_real = torch.empty(output_shape, dtype=torch.float32, device=input_tensor.device)
    output_imag = torch.empty(output_shape, dtype=torch.float32, device=input_tensor.device)

    # Handle the case where dim is not the last dimension
    dim_to_transpose = None
    if dim != input_tensor.ndim - 1:
        dim_to_transpose = dim
        input_tensor = torch.transpose(input_tensor, dim, input_tensor.ndim - 1)

    # Reshape to 1D for FFT
    input_1d = input_tensor.flatten()
    output_real_1d = output_real.flatten()
    output_imag_1d = output_imag.flatten()

    # Use a vectorized kernel where each thread computes multiple output elements
    # Use grid of BLOCK_SIZE threads, each computing multiple outputs
    BLOCK_SIZE = 128
    grid = (triton.cdiv(output_size, BLOCK_SIZE),)

    @triton.jit
    def _fft_r2c_vectorized_kernel(
        input_ptr,
        output_real_ptr,
        output_imag_ptr,
        n_fft: tl.constexpr,
        output_size: tl.constexpr,
        BLOCK_SIZE: tl.constexpr,
        PI: tl.constexpr,
    ):
        # Each program handles a block of outputs
        pid = tl.program_id(0)
        block_start = pid * BLOCK_SIZE
        offs = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offs < output_size

        # Initialize accumulators for all outputs in this block
        real_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
        imag_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

        # Loop over input elements
        for n_idx in range(n_fft):
            # Load input value for all threads
            x = tl.load(input_ptr + n_idx)

            # Load current twiddle factor for each output
            angle = -2.0 * PI * tl.cast(offs, tl.float32) * tl.cast(n_idx, tl.float32) / tl.cast(n_fft, tl.float32)
            twiddle_real = tl.cos(angle)
            twiddle_imag = tl.sin(angle)

            # Accumulate
            real_acc = real_acc + x * twiddle_real
            imag_acc = imag_acc + x * twiddle_imag

        # Store results
        tl.store(output_real_ptr + offs, real_acc, mask=mask)
        tl.store(output_imag_ptr + offs, imag_acc, mask=mask)

    _fft_r2c_vectorized_kernel[grid](
        input_1d,
        output_real_1d,
        output_imag_1d,
        n,
        output_size,
        BLOCK_SIZE,
        math.pi,
    )

    # Apply normalization if needed
    if normalization == 1:  # forward
        output_real_1d = output_real_1d / n
        output_imag_1d = output_imag_1d / n
    elif normalization == 2:  # ortho
        output_real_1d = output_real_1d / (n ** 0.5)
        output_imag_1d = output_imag_1d / (n ** 0.5)

    # Combine into complex tensor
    output = torch.complex(output_real, output_imag)

    # If we transposed, transpose back
    if dim_to_transpose is not None:
        output = torch.transpose(output, dim_to_transpose, output.ndim - 1)

    return output


def _fft_r2c_nd_triton(input_tensor, dim, normalization, onesided):
    """N-D real-to-complex FFT using Triton for each FFT along dim."""
    dim = dim[0] if isinstance(dim, (list, tuple)) else dim
    return _fft_r2c_1d_triton(input_tensor, dim, normalization, onesided)


def fft_r2c(input: torch.Tensor, dim, normalization, onesided):
    """Real-to-complex FFT.

    Args:
        input: Real-valued input tensor
        dim: Dimension to perform FFT along
        normalization: 0 = none, 1 = forward, 2 = ortho
        onesided: If True, return only the first n/2+1 elements

    Returns:
        Complex tensor containing the FFT result
    """
    logger.debug("GEMS FFT_R2C")

    # Normalize dim
    if isinstance(dim, int):
        dim = [dim]
    dim = [d if d >= 0 else d + input.ndim for d in dim]

    # Handle different cases
    if len(dim) == 1:
        return _fft_r2c_1d_triton(input, dim[0], normalization, onesided)
    else:
        return _fft_r2c_nd_triton(input, dim, normalization, onesided)


# Alias for backwards compatibility
_fft_r2c = fft_r2c