# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _functional_assert_async_kernel(
    x_ptr,
    y_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask)
    tl.store(y_ptr + offsets, x, mask=mask)


def _functional_assert_async(self: torch.Tensor, assert_msg: str, dep_token: torch.Tensor):
    logger.debug("GEMS _FUNCTIONAL_ASSERT_ASYNC")
    """
    Wrapper for aten::_functional_assert_async
    Functional assert async operator - returns the input tensor as a pass-through.
    """
    if self.is_contiguous():
        n_elements = self.numel()
        if n_elements > 0:
            grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
            with torch_device_fn.device(self.device):
                _functional_assert_async_kernel[grid](
                    self, self, n_elements, BLOCK_SIZE=1024
                )
        return self

    # If not contiguous, use copy
    out = torch.empty_like(self)
    n_elements = out.numel()
    if n_elements == 0:
        return out
    src = self.contiguous() if not self.is_contiguous() else self
    if not out.is_contiguous():
        out = out.contiguous()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(self.device):
        _functional_assert_async_kernel[grid](src, out, n_elements, BLOCK_SIZE=1024)
    return out