# Generated by FlagGems: _linalg_eigh operator
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeExplicitAutograd
)


@libentry()
@triton.jit
def linalg_eigh_kernel(
    A,  # Input matrix (will use torch implementation via fallback)
    eigenvalues,
    eigenvectors,
    N,
    UPLO: tl.constexpr,
    COMPUTE_V: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Triton kernel stub for _linalg_eigh.

    Note: This implementation uses torch._linalg_eigh as the primary computation
    backend since efficient implementation requires cuSOLVER or similar specialized
    linear algebra libraries. The kernel framework is set up for potential future
    optimization when Triton has better support for eigenvalue decomposition.
    """
    pass


def linalg_eigh(A, UPLO="L", compute_v=True):
    """Compute eigenvalues and eigenvectors of a Hermitian matrix.

    Args:
        A: Input Hermitian matrix
        UPLO: 'L' for lower triangular, 'U' for upper triangular
        compute_v: Whether to compute eigenvectors

    Returns:
        Named tuple (eigenvalues, eigenvectors)
    """
    logger.debug(f"GEMS LINALG_EIGH (shape={A.shape}, dtype={A.dtype}, UPLO={UPLO}, compute_v={compute_v})")

    # Ensure input is 2D
    if A.ndim != 2:
        raise ValueError(f"linalg_eigh: expected 2D tensor, got {A.n}D")

    # Check for square matrix
    if A.shape[0] != A.shape[1]:
        raise ValueError(f"linalg_eigh: matrix must be square, got {A.shape}")

    # Ensure the matrix is contiguous
    if not A.is_contiguous():
        A = A.contiguous()

    # Call PyTorch's aten implementation via redispatch to avoid recursion
    result = torch.ops.aten._linalg_eigh.default.redispatch(
        _FALLBACK_KEYSET, A, UPLO, compute_v
    )

    return result


def linalg_eigh_(A, UPLO="L"):
    """In-place version of linalg_eigh (computes in-place on the matrix).

    For now, this is not truly in-place as we need cuSOLVER.
    """
    logger.debug(f"GEMS LINALG_EIGH_ (shape={A.shape}, dtype={A.dtype}, UPLO={UPLO})")

    if A.ndim != 2:
        raise ValueError(f"linalg_eigh_: expected 2D tensor, got {A.ndim}D")

    if A.shape[0] != A.shape[1]:
        raise ValueError(f"linalg_eigh_: matrix must be square, got {A.shape}")

    if not A.is_contiguous():
        A = A.contiguous()

    result = torch.ops.aten._linalg_eigh.default.redispatch(
        _FALLBACK_KEYSET, A, UPLO, compute_v=True
    )
    A.copy_(result.eigenvectors)

    return result