# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, 2, "DEFAULT")])
@triton.jit
def prelu_kernel_backward_grad_x(grad_output, x, weight):
    # grad_x = where(x > 0, grad_output, weight * grad_output)
    return tl.where(x > 0, grad_output, weight * grad_output)


@pointwise_dynamic(promotion_methods=[(0, 1, 2, "DEFAULT")])
@triton.jit
def prelu_kernel_backward_grad_weight(grad_output, x, weight):
    # grad_weight = where(x > 0, 0, x * grad_output)
    return tl.where(x > 0, 0, x * grad_output)


def _prelu_kernel_backward(grad_output, self, weight):
    logger.debug("GEMS _PRELU_KERNEL_BACKWARD")

    if not (grad_output.is_cuda and self.is_cuda and weight.is_cuda):
        raise AssertionError("All tensors must be CUDA tensors.")

    # Ensure dtype match
    if weight.dtype != self.dtype:
        weight = weight.to(dtype=self.dtype)
    if grad_output.dtype != self.dtype:
        grad_output = grad_output.to(dtype=self.dtype)

    # Make contiguous
    grad_output = grad_output.contiguous()
    self = self.contiguous()
    weight = weight.contiguous()

    # Compute grad_x
    grad_x = prelu_kernel_backward_grad_x(grad_output, self, weight)

    # Compute grad_weight (element-wise, same shape as input)
    grad_weight = prelu_kernel_backward_grad_weight(grad_output, self, weight)

    return grad_x, grad_weight