# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.heuristics({"BLOCK_SIZE": lambda args: 128})
@triton.jit
def diagonal_copy_2d_kernel(
    input_ptr,
    output_ptr,
    M,
    N,
    stride_m,
    stride_n,
    offset,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Kernel for 2D diagonal_copy.
    For input[M, N], output[k] where k corresponds to diagonal element.
    """
    pid = tle.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = pid < n_elements

    # Compute the diagonal index
    # For offset >= 0: diag_idx = pid, valid if diag_idx < min(M, N - offset)
    # For offset < 0: diag_idx = pid, valid if diag_idx < min(M + offset, N)

    # Compute the input indices
    # i = diag_idx + max(0, -offset)
    # j = diag_idx + max(0, offset)
    # flat index = i * stride_m + j * stride_n

    i_offset = tl.maximum(0, -offset)
    j_offset = tl.maximum(0, offset)

    # diag_idx = pid
    i_idx = pid + i_offset
    j_idx = pid + j_offset

    # Validate bounds
    valid = (i_idx < M) and (j_idx < N)

    input_offset = i_idx * stride_m + j_idx * stride_n

    value = tl.load(input_ptr + input_offset, mask=valid, other=0.0)
    tl.store(output_ptr + pid, value, mask=mask and valid)


@libentry()
@triton.heuristics({"BLOCK_SIZE": lambda args: 128})
@triton.jit
def diagonal_copy_3d_kernel(
    input_ptr,
    output_ptr,
    dim1,
    dim2,
    offset,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Kernel for 3D diagonal_copy.
    This handles the case where we take diagonal of two dimensions.
    """
    pid = tle.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = pid < n_elements


def diagonal_copy(input: torch.Tensor, offset: int = 0, dim1: int = 0, dim2: int = 1):
    """
    Performs the same operation as torch.diagonal, but returns a copy instead of a view.
    """
    logger.debug("GEMS DIAGONAL_COPY")

    # Normalize dims
    dim1 = dim1 % input.ndim
    dim2 = dim2 % input.ndim

    # Compute output shape
    dim1_size = input.shape[dim1]
    dim2_size = input.shape[dim2]

    if offset >= 0:
        diag_len = min(dim1_size, dim2_size - offset)
    else:
        diag_len = min(dim1_size + offset, dim2_size)

    if diag_len <= 0:
        return torch.empty(0, dtype=input.dtype, device=input.device)

    # Build output shape: all dims except dim1 and dim2, plus diag_len
    output_shape = []
    for i, s in enumerate(input.shape):
        if i != dim1 and i != dim2:
            output_shape.append(s)
    output_shape.append(diag_len)

    output = torch.empty(output_shape, dtype=input.dtype, device=input.device)

    if input.ndim == 2 and dim1 == 0 and dim2 == 1:
        # 2D case with default dims - use optimized kernel
        M, N = input.shape
        stride_m = input.stride(0)
        stride_n = input.stride(1)

        grid = lambda meta: (triton.cdiv(diag_len, meta["BLOCK_SIZE"]),)

        diagonal_copy_2d_kernel[grid](
            input, output, M, N, stride_m, stride_n, offset, diag_len
        )
        return output
    else:
        # For general case, use torch.diagonal + copy
        # This is the fallback for complex cases
        diag = torch.diagonal(input, offset, dim1, dim2)
        from flag_gems.ops.copy import copy

        return copy(output, diag)