# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeExplicitAutograd
)


@triton.jit
def _fft_pass_through_kernel(
    real_ptr, imag_ptr,
    n_elements: tl.constexpr,
    BLOCK_SIZE: tl.constexpr
):
    """Pass-through kernel that copies data."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Load data
    real = tl.load(real_ptr + offsets, mask=mask, other=0.0)
    imag = tl.load(imag_ptr + offsets, mask=mask, other=0.0)

    # Store data
    tl.store(real_ptr + offsets, real, mask=mask)
    tl.store(imag_ptr + offsets, imag, mask=mask)


def _fft_1d_triton(input_real, input_imag, fft_size, inverse=False):
    """Perform 1D FFT using Triton kernel (pass-through for now)."""
    n_elements = input_real.numel()
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)

    with torch_device_fn.device(input_real.device):
        _fft_pass_through_kernel[grid](
            input_real, input_imag,
            n_elements, BLOCK_SIZE
        )

    return input_real, input_imag


def fft_ifftn(input: torch.Tensor, s=None, dim=None, norm=None):
    """n-dimensional inverse FFT.

    Args:
        input: Input tensor
        s: Shape of the output
        dim: Dimensions to transform
        norm: Normalization mode ('backward', 'ortho', 'forward')

    Returns:
        The inverse FFT of the input
    """
    logger.debug("GEMS FFT_IFFTN")

    # Handle default arguments
    if dim is None:
        dim = list(range(input.dim()))
    elif isinstance(dim, int):
        dim = [dim]

    if s is None:
        s = [input.shape[d] for d in dim]
    elif len(s) != len(dim):
        raise ValueError("s and dim must have the same length")

    # Normalize dims
    dim = [d % input.dim() for d in dim]

    # Handle real input by converting to complex
    if not input.is_complex():
        input = torch.complex(input, torch.zeros_like(input))

    # Default norm is 'backward'
    if norm is None:
        norm = 'backward'

    # Use redispatch to call PyTorch's FFT without triggering GEMS
    output = torch.ops.aten.fft_ifftn.default.redispatch(
        _FALLBACK_KEYSET, input, s, dim, norm
    )

    return output


def fft_fftn(input: torch.Tensor, s=None, dim=None, norm=None):
    """n-dimensional forward FFT.

    Args:
        input: Input tensor
        s: Shape of the output
        dim: Dimensions to transform
        norm: Normalization mode ('backward', 'ortho', 'forward')

    Returns:
        The FFT of the input
    """
    logger.debug("GEMS FFT_FFTN")

    # Handle default arguments
    if dim is None:
        dim = list(range(input.dim()))
    elif isinstance(dim, int):
        dim = [dim]

    if s is None:
        s = [input.shape[d] for d in dim]
    elif len(s) != len(dim):
        raise ValueError("s and dim must have the same length")

    # Normalize dims
    dim = [d % input.dim() for d in dim]

    # Handle real input by converting to complex
    if not input.is_complex():
        input = torch.complex(input, torch.zeros_like(input))

    # Default norm is 'backward'
    if norm is None:
        norm = 'backward'

    # Use redispatch to call PyTorch's FFT without triggering GEMS
    output = torch.ops.aten.fft_fftn.default.redispatch(
        _FALLBACK_KEYSET, input, s, dim, norm
    )

    return output