# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _fft_ihfft_kernel(
    input_ptr, output_real_ptr, output_imag_ptr,
    n_fft: tl.constexpr, n_output: tl.constexpr, n_batch: tl.constexpr
):
    # Each program computes one output frequency bin for one batch element
    # Total programs = n_output * n_batch
    pid = tl.program_id(axis=0)

    # Decode program id: (batch_idx, k_idx)
    batch_idx = pid // n_output
    k = pid % n_output

    if batch_idx >= n_batch:
        return

    # Compute the DFT for this frequency bin
    # X[k] = sum(x[n] * exp(-2*pi*i*k*n/N)) for n in [0, N)
    real_sum = 0.0
    imag_sum = 0.0

    two_pi_k_div_n = -2.0 * 3.141592653589793 * k / n_fft

    # Process input elements
    # Unroll by 8 for better efficiency
    n_iter = n_fft // 8
    remainder = n_fft % 8

    for i in range(n_iter):
        idx = i * 8

        # Load 8 input values
        x0 = tl.load(input_ptr + batch_idx * n_fft + idx)
        x1 = tl.load(input_ptr + batch_idx * n_fft + idx + 1)
        x2 = tl.load(input_ptr + batch_idx * n_fft + idx + 2)
        x3 = tl.load(input_ptr + batch_idx * n_fft + idx + 3)
        x4 = tl.load(input_ptr + batch_idx * n_fft + idx + 4)
        x5 = tl.load(input_ptr + batch_idx * n_fft + idx + 5)
        x6 = tl.load(input_ptr + batch_idx * n_fft + idx + 6)
        x7 = tl.load(input_ptr + batch_idx * n_fft + idx + 7)

        # Compute angles
        angle0 = two_pi_k_div_n * idx
        angle1 = two_pi_k_div_n * (idx + 1)
        angle2 = two_pi_k_div_n * (idx + 2)
        angle3 = two_pi_k_div_n * (idx + 3)
        angle4 = two_pi_k_div_n * (idx + 4)
        angle5 = two_pi_k_div_n * (idx + 5)
        angle6 = two_pi_k_div_n * (idx + 6)
        angle7 = two_pi_k_div_n * (idx + 7)

        # Accumulate real and imaginary parts
        real_sum += x0 * tl.cos(angle0) + x1 * tl.cos(angle1) + x2 * tl.cos(angle2) + x3 * tl.cos(angle3)
        real_sum += x4 * tl.cos(angle4) + x5 * tl.cos(angle5) + x6 * tl.cos(angle6) + x7 * tl.cos(angle7)
        imag_sum += -x0 * tl.sin(angle0) - x1 * tl.sin(angle1) - x2 * tl.sin(angle2) - x3 * tl.sin(angle3)
        imag_sum += -x4 * tl.sin(angle4) - x5 * tl.sin(angle5) - x6 * tl.sin(angle6) - x7 * tl.sin(angle7)

    # Handle remainder
    for i in range(remainder):
        idx = n_iter * 8 + i
        x = tl.load(input_ptr + batch_idx * n_fft + idx)
        angle = two_pi_k_div_n * idx
        real_sum += x * tl.cos(angle)
        imag_sum += -x * tl.sin(angle)

    # Store result
    out_idx = batch_idx * n_output + k
    tl.store(output_real_ptr + out_idx, real_sum)
    tl.store(output_imag_ptr + out_idx, imag_sum)


def fft_ihfft(input: torch.Tensor, n: int = None, dim: int = -1, norm=None):
    logger.debug("GEMS FFT_IHFFT")

    # Ensure input is contiguous
    input = input.contiguous()

    # Handle default dim
    if dim == -1:
        dim = input.dim() - 1

    # Get the size along the FFT dimension
    n_fft = input.shape[dim] if n is None else n

    # Handle n parameter - pad or truncate input if needed
    if n is not None and n != input.shape[dim]:
        if n > input.shape[dim]:
            # Pad with zeros
            pad_size = list(input.shape)
            pad_size[dim] = n - input.shape[dim]
            padding = torch.zeros(pad_size, dtype=input.dtype, device=input.device)
            input = torch.cat([input, padding], dim=dim)
        else:
            # Truncate
            slices = [slice(None)] * input.dim()
            slices[dim] = slice(0, n)
            input = input[tuple(slices)]

    # Output size for real input is n_fft//2 + 1
    n_output = n_fft // 2 + 1

    # Compute batch size (product of all dimensions before the FFT dim)
    n_batch = 1
    for i in range(dim):
        n_batch *= input.shape[i]

    # Build output shape
    output_shape = list(input.shape)
    output_shape[dim] = n_output

    # Flatten the input for processing
    input_flat = input.reshape(n_batch, n_fft)

    # Allocate output buffers
    output_real = torch.zeros((n_batch, n_output), dtype=torch.float32, device=input.device)
    output_imag = torch.zeros((n_batch, n_output), dtype=torch.float32, device=input.device)

    # Launch kernel
    # Each program computes one output frequency bin for one batch element
    grid = (n_batch * n_output,)

    _fft_ihfft_kernel[grid](
        input_flat, output_real, output_imag,
        n_fft, n_output, n_batch
    )

    # Handle norm parameter (default is backward, which divides by N)
    # Scale real and imaginary parts separately to avoid complex type issues
    scale = 1.0
    if norm is None or norm == "backward":
        scale = 1.0 / n_fft
    elif norm == "ortho":
        scale = 1.0 / math.sqrt(n_fft)

    if scale != 1.0:
        output_real = output_real * scale
        output_imag = output_imag * scale

    # Combine real and imaginary parts
    output = torch.complex(output_real, output_imag)

    # Reshape to output shape
    output = output.reshape(output_shape)

    return output