# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)

# Fallback keyset to bypass dispatcher and call original implementation
_FALLBACK_KEYSET = torch._C.DispatchKeySet(
    torch._C.DispatchKey.CompositeExplicitAutograd
)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def _fft_fft_kernel(x, output):
    # This is a placeholder kernel - actual FFT computation uses torch.fft.fft
    # For FFT operations, we rely on torch's cuFFT implementation
    pass


def fft_fft(input: torch.Tensor, n: int = None, dim: int = -1, norm: str = None):
    logger.debug("GEMS fft_fft")
    # Use redispatch to bypass the dispatcher and call the original implementation
    return torch.ops.aten.fft_fft.default.redispatch(
        _FALLBACK_KEYSET, input, n, dim, norm
    )