# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils.pointwise_dynamic import pointwise_dynamic

logger = logging.getLogger(__name__)


def fft_irfftn(input: torch.Tensor, s=None, dim=None, norm="backward"):
    """
    Compute the inverse of torch.fft.rfftn.

    Args:
        input: Complex tensor (half-Hermitian from rfftn)
        s: Output size for each dimension
        dim: Dimensions to transform
        norm: Normalization mode ("forward", "backward", "ortho")

    Returns:
        Real tensor
    """
    logger.debug("GEMS FFT_IRFFTN")

    if not input.is_complex():
        raise ValueError("Input must be a complex tensor")

    # Handle default dim (last dimension or all dimensions)
    if dim is None:
        if s is not None:
            dim = tuple(range(-len(s), 0))
        else:
            dim = tuple(range(input.dim()))

    # Convert dim to tuple if it's a single int
    if isinstance(dim, int):
        dim = (dim,)

    # Handle s parameter - output size for each transformed dimension
    if s is None:
        # Default: s[i] = 2 * (input.shape[dim[i]] - 1)
        s = []
        for d in dim:
            if d < 0:
                d = input.dim() + d
            s.append(2 * (input.shape[d] - 1))
        s = tuple(s)

    # For simplicity, only handle the case where we transform the last dimension
    # Multi-dimensional case is not supported yet
    if len(dim) != 1 or dim[0] != -1:
        raise NotImplementedError(
            "fft_irfftn only supports transforming the last dimension for now"
        )

    # Now dim[0] is -1 (last dimension)
    d = input.dim() - 1  # Convert to positive index
    n_fft = s[0]
    input_len = input.shape[d]

    # Verify input is half-Hermitian
    expected_len = n_fft // 2 + 1
    if input_len != expected_len:
        raise ValueError(
            f"Input shape at dim {d} is {input_len}, expected {expected_len} for n_fft={n_fft}"
        )

    # Get the complex input as real/imag separate tensors
    input_real = torch.real(input).contiguous()
    input_imag = torch.imag(input).contiguous()

    # Calculate output shape
    output_shape = list(input.shape)
    output_shape[d] = n_fft
    output_shape = tuple(output_shape)

    # Create output tensor
    output = torch.empty(output_shape, dtype=torch.float32, device=input.device)

    # Get the total number of 1D FFTs to compute
    # This is the product of all dimensions except the transformed one
    n_ffts = 1
    for i in range(input.dim() - 1):
        n_ffts *= input.shape[i]

    n_output = n_fft

    # Handle 1D case separately
    if input.dim() == 1:
        grid = (n_output, )
        _irfft_kernel[grid](
            input_real,
            input_imag,
            output,
            n_fft,
            n_output,
        )
    else:
        # Multi-dimensional case: transform last dimension
        # Already contiguous, just need to process each 1D FFT
        for i in range(n_ffts):
            grid = (n_output, )
            _irfft_kernel[grid](
                input_real[i, :],
                input_imag[i, :],
                output[i, :],
                n_fft,
                n_output,
            )

    # Apply normalization
    if norm == "backward":
        output = output / n_fft
    elif norm == "ortho":
        output = output / (n_fft ** 0.5)
    # norm == "forward" means no normalization

    return output


# Use a fixed BLOCK_SIZE since dynamic loop is not supported
BLOCK_SIZE = 64


@triton.jit
def _irfft_kernel(input_real, input_imag, output, n_fft: tl.constexpr, n_output: tl.constexpr):
    """
    Optimized inverse FFT kernel for 1D case.
    For n_fft points, input has n_fft//2 + 1 complex values.
    The formula is:
    output[i] = input[0].real + 2 * sum_{k=1}^{n_fft//2-1} (re[k]*cos(2*pi*k*i/n) - im[k]*sin(2*pi*k*i/n)) + input[n_fft//2].real * cos(pi*i)
    """
    # Get the position
    pid = tl.program_id(0)
    output_idx = pid

    # Precompute 2*pi/n_fft
    two_pi_over_n = 2.0 * 3.141592653589793 / n_fft

    # DC component (k=0)
    result = tl.load(input_real + 0).to(tl.float32)

    # Positive frequencies (k=1 to n_fft//2-1)
    for k in range(1, n_fft // 2):
        re = tl.load(input_real + k).to(tl.float32)
        im = tl.load(input_imag + k).to(tl.float32)
        angle = two_pi_over_n * k * output_idx
        result = result + 2.0 * (re * tl.cos(angle) - im * tl.sin(angle))

    # Handle Nyquist frequency if n_fft is even
    # Nyquist is at index n_fft//2
    if n_fft % 2 == 0:
        nyquist_idx = n_fft // 2
        nyquist_re = tl.load(input_real + nyquist_idx).to(tl.float32)
        # cos(pi * i) = (-1)^i
        if output_idx % 2 == 0:
            result = result + nyquist_re
        else:
            result = result - nyquist_re

    tl.store(output + output_idx, result)


def fft_irfftn_(input: torch.Tensor, s=None, dim=None, norm="backward"):
    """
    In-place version of fft_irfftn (returns a new tensor).
    """
    return fft_irfftn(input, s=s, dim=dim, norm=norm)