# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

_pow = tl_extra_shim.pow


@triton.jit
def igamma_kernel_(
    a_ptr,
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    a = tl.load(a_ptr + offsets, mask=mask)
    x = tl.load(x_ptr + offsets, mask=mask)

    # Convert to float32 for computation
    a_f32 = a.to(tl.float32)
    x_f32 = x.to(tl.float32)

    # Handle edge case x == 0
    result_zero = x_f32 == 0.0

    # Constants
    pi = 3.1415926535897932384626433832795028841971
    g = 5.5

    # ========== log_gamma computation using Lanczos ==========
    # Reflection for x < 0.5
    reflect_mask = a_f32 < 0.5
    x_refl = tl.where(reflect_mask, 1.0 - a_f32, a_f32)

    t = x_refl - 1.0
    p = (
        0.99999999999980993
        + 676.5203681218851 / (t + 1.0)
        + -1259.1392167224028 / (t + 2.0)
        + 771.32342877765313 / (t + 3.0)
        + -176.61502916214059 / (t + 4.0)
        + 12.507343278686905 / (t + 5.0)
        + -0.13857109526572012 / (t + 6.0)
        + 9.9843695780195716e-6 / (t + 7.0)
        + 1.5056327351493116e-7 / (t + 8.0)
    )
    sqrt_2pi = 2.5066282746310005024157652848110
    log_gamma_a = (
        (x_refl + 0.5) * tl.log(x_refl + g - 0.5) - (x_refl + g - 0.5) + tl.log(sqrt_2pi * p)
    )
    log_gamma_a = tl.where(
        reflect_mask,
        tl.log(pi) - tl.log(tl.abs(tl.sin(pi * a_f32))) - log_gamma_a,
        log_gamma_a,
    )

    # ========== Compute log(ax) ==========
    log_ax = a_f32 * tl.log(x_f32) - x_f32 - log_gamma_a
    ax = tl.exp(log_ax)

    # ========== Series expansion for small x (x < a + 1) ==========
    # P(a,x) = x^a * e^{-x} * SUM_{n=0}INF x^n / (a*(a+1)*...*(a+n))
    small_x = x_f32 < (a_f32 + 1.0)

    # Series terms: fixed 60 iterations
    series_result = _pow(a_f32, -1.0)
    series_term = _pow(a_f32, -1.0)
    n = 1.0
    for i in range(60):
        series_term = series_term * x_f32 / n
        delta = series_term / (a_f32 + n)
        series_result = series_result + delta
        n = n + 1.0
    series_res = ax * series_result

    # ========== Continued fraction for larger x (x >= a + 1) ==========
    # Lentz's method for P(a,x) = 1 - Q(a,x)
    f = 1e-30
    C = f
    D = 0.0
    bn = x_f32 - a_f32 + 1.0
    D = bn + a_f32 * D
    D = tl.where(tl.abs(D) < 1e-30, 1e-30, D)
    C = bn + a_f32 / C
    C = tl.where(tl.abs(C) < 1e-30, 1e-30, C)
    D = _pow(D, -1.0)
    f = f * C * D

    # Iterate fixed 60 times
    n = 1.0
    for i in range(60):
        bn = x_f32 + n - a_f32 + 1.0
        D = bn + a_f32 * D
        D = tl.where(tl.abs(D) < 1e-30, 1e-30, D)
        C = bn + a_f32 / C
        C = tl.where(tl.abs(C) < 1e-30, 1e-30, C)
        D = _pow(D, -1.0)
        delta = C * D
        f = f * delta
        n = n + 1.0

    cf_res = 1.0 - tl.exp(log_ax) * f

    # ========== Select result based on x vs a ==========
    result = tl.where(result_zero, 0.0, tl.where(small_x, series_res, cf_res))

    # Clamp to [0, 1] for numerical stability
    result = tl.minimum(result, 1.0)
    result = tl.maximum(result, 0.0)

    # Convert back and store
    result = result.to(a.dtype)
    tl.store(out_ptr + offsets, result, mask=mask)


def igamma_(self, other):
    """In-place regularized lower incomplete gamma function P(a, x).

    Computes P(a, x) = γ(a, x) / Γ(a) where a=self and x=other.
    The result is stored in self (in-place operation).
    """
    logger.debug("GEMS IGAMMA_")

    if not isinstance(self, torch.Tensor):
        raise TypeError("igamma_ expects a torch.Tensor as the first argument")
    if not isinstance(other, torch.Tensor):
        raise TypeError("igamma_ expects a torch.Tensor as the second argument")

    # Handle empty tensors
    if self.numel() == 0:
        return self

    # Broadcast shapes
    output_shape = torch.broadcast_shapes(self.shape, other.shape)
    n_elements = 1
    for dim in output_shape:
        n_elements *= dim

    if n_elements == 0:
        return self

    # Broadcast and make contiguous
    a_tensor = self.expand(output_shape).contiguous()
    x_tensor = other.expand(output_shape).contiguous()

    # Allocate output tensor
    result = torch.empty_like(a_tensor)

    # Launch kernel
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(a_tensor.device):
        igamma_kernel_[grid](
            a_tensor, x_tensor, result, n_elements, BLOCK_SIZE=1024
        )

    # Copy result back to self (in-place)
    self.copy_(result)
    return self