# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device, torch_device_fn
from flag_gems.utils import libentry, libtuner
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)


@triton.jit
def paste_u64(hi: tl.uint32, lo: tl.uint32):
    return (hi.to(tl.uint64) << 32) | lo.to(tl.uint64)


@triton.jit
def transform_lognormal_f32(u0, u1, mean, std):
    """Transform two uniform randoms to log-normal using Box-Muller (f32)."""
    # Box-Muller: z = sqrt(-2*ln(u0)) * cos(2*pi*u1)
    # Avoid log(0) by clamping u0
    u0_clamped = tl.where(u0 <= 0.0, 1.0e-7, u0)
    log_u0 = tl.log(u0_clamped)
    cos_part = tl.cos(6.28318530718 * u1)
    z0 = tl.sqrt(-2.0 * log_u0) * cos_part
    return tl.exp(mean + std * z0)


@triton.jit
def transform_lognormal_f64(u0_hi, u0_lo, u1_hi, u1_lo, mean, std):
    """Transform two uniform randoms (as uint64 pairs) to log-normal (f64)."""
    u0 = uint_to_uniform_float(paste_u64(u0_hi, u0_lo))
    u1 = uint_to_uniform_float(paste_u64(u1_hi, u1_lo))
    u0_clamped = tl.where(u0 <= 0.0, 1.0e-7, u0)
    log_u0 = tl.log(u0_clamped)
    cos_part = tl.cos(6.283185307179586 * u1)
    z0 = tl.sqrt(-2.0 * log_u0) * cos_part
    return tl.exp(mean + std * z0)


@libentry()
@libtuner(
    configs=[
        triton.Config({"BLOCK": 64}, num_warps=2, num_stages=2),
        triton.Config({"BLOCK": 128}, num_warps=2, num_stages=2),
        triton.Config({"BLOCK": 256}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK": 512}, num_warps=4, num_stages=3),
        triton.Config({"BLOCK": 1024}, num_warps=8, num_stages=3),
    ],
    key=["N"],
)
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def fused_lognormal_kernel_f32(
    out_ptr, N, mean, std, philox_seed, philox_offset, BLOCK: tl.constexpr
):
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)

    pid = tl.program_id(0)
    i = pid * BLOCK + tl.arange(0, BLOCK)
    c0 += i
    z = c0 * 0
    r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, z, z)

    # Use r0,r1 as pair for first output, r2,r3 as pair for second
    u0_0 = uint_to_uniform_float(r0)
    u1_0 = uint_to_uniform_float(r1)
    y0 = transform_lognormal_f32(u0_0, u1_0, mean, std)

    u0_1 = uint_to_uniform_float(r2)
    u1_1 = uint_to_uniform_float(r3)
    y1 = transform_lognormal_f32(u0_1, u1_1, mean, std)

    # Store two values per thread
    start = pid.to(tl.uint64) * BLOCK * 2
    off0 = start + tl.arange(0, BLOCK)
    off1 = off0 + BLOCK

    tl.store(out_ptr + off0, y0, mask=off0 < N)
    tl.store(out_ptr + off1, y1, mask=off1 < N)


@libentry()
@libtuner(
    configs=[
        triton.Config({"BLOCK": 64}, num_warps=2, num_stages=2),
        triton.Config({"BLOCK": 128}, num_warps=2, num_stages=2),
        triton.Config({"BLOCK": 256}, num_warps=4, num_stages=2),
        triton.Config({"BLOCK": 512}, num_warps=4, num_stages=3),
    ],
    key=["N"],
)
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def fused_lognormal_kernel_f64(
    out_ptr, N, mean, std, philox_seed, philox_offset, BLOCK: tl.constexpr
):
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)

    pid = tl.program_id(0)
    i = pid * BLOCK + tl.arange(0, BLOCK)
    c0 += i
    z = c0 * 0
    r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, z, z)

    # r0,r2 form first uint64 pair, r1,r3 form second
    y0 = transform_lognormal_f64(r0, r2, r1, r3, mean, std)

    start = pid.to(tl.uint64) * BLOCK
    off0 = start + tl.arange(0, BLOCK)

    tl.store(out_ptr + off0, y0, mask=off0 < N)


def log_normal_(x, mean: float = 1.0, std: float = 2.0, *, generator=None):
    logger.debug("GEMS LOG_NORMAL_")

    dtype = x.dtype
    device = x.device
    inplace = x.is_contiguous()
    assert dtype in (torch.float16, torch.bfloat16, torch.float32, torch.float64)

    N = x.numel()
    if N == 0:
        return x

    mean_scalar = float(mean)
    std_scalar = float(std)

    out = x if inplace else torch.empty_like(x)

    if dtype is torch.float64:
        UNROLL = 1
        grid = lambda meta: (triton.cdiv(N, meta["BLOCK"] * UNROLL),)
        increment = triton.cdiv(N, UNROLL)
        philox_seed, philox_offset = philox_backend_seed_offset(
            increment, generator=generator
        )
        with torch_device_fn.device(device):
            fused_lognormal_kernel_f64[grid](
                out, N, mean_scalar, std_scalar, philox_seed, philox_offset
            )
    else:
        UNROLL = 2
        grid = lambda meta: (triton.cdiv(N, meta["BLOCK"] * UNROLL),)
        increment = triton.cdiv(N, UNROLL)
        philox_seed, philox_offset = philox_backend_seed_offset(
            increment, generator=generator
        )
        with torch_device_fn.device(device):
            fused_lognormal_kernel_f32[grid](
                out, N, mean_scalar, std_scalar, philox_seed, philox_offset
            )

    if not inplace:
        x.copy_(out)
    return x