# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def polygamma_digamma_kernel(
    x_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for polygamma(n=0) = digamma"""
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    pi = 3.1415926535897932384626433832795028841971

    # Reflect x < 0.5 to x >= 0.5
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Use recurrence to shift xr to >= 8
    result = tl.zeros_like(x_f32)
    y = xr

    for _ in range(8):
        m = y < 8.0
        result = result - tl.where(m, 1.0 / y, 0.0)
        y = tl.where(m, y + 1.0, y)

    # Asymptotic expansion
    r = 1.0 / y
    r2 = r * r
    r4 = r2 * r2
    r6 = r4 * r2
    series = (
        (-0.5 * r)
        + (-1.0 / 12.0) * r2
        + (1.0 / 120.0) * r4
        + (-1.0 / 252.0) * r6
    )
    psi_y = tl.log(y) + result + series

    # Apply reflection: psi(x) = psi(1-x) - pi*cot(pi*x)
    cot_term = tl.cos(pi * x_f32) / tl.sin(pi * x_f32)
    result_final = tl.where(reflect_mask, psi_y - pi * cot_term, psi_y)

    result_final = result_final.to(x.dtype)
    tl.store(output_ptr + offsets, result_final, mask=mask)


@triton.jit
def polygamma_trigamma_kernel(
    x_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for polygamma(n=1) = trigamma"""
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    pi = 3.1415926535897932384626433832795028841971

    # Reflect x < 0.5 to x >= 0.5
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Use recurrence to shift xr to >= 8
    # psi'(x+1) = psi'(x) - 1/x^2
    result = tl.zeros_like(x_f32)
    y = xr

    for _ in range(8):
        m = y < 8.0
        result = result + tl.where(m, 1.0 / (y * y), 0.0)
        y = tl.where(m, y + 1.0, y)

    # Asymptotic expansion: psi'(x) ~ 1/x + 1/(2x^2) + 1/(6x^3) - ...
    r = 1.0 / y
    r2 = r * r
    r3 = r2 * r
    r4 = r3 * r
    r5 = r4 * r
    series = (
        r
        + 0.5 * r2
        + (1.0 / 6.0) * r3
        + (-1.0 / 30.0) * r5
    )
    psi_y = series

    # Apply reflection: psi'(x) + psi'(1-x) = pi^2/sin^2(pi*x)
    sin_term = tl.sin(pi * x_f32)
    csc2 = pi * pi / (sin_term * sin_term)
    result_final = tl.where(reflect_mask, psi_y + csc2, psi_y)

    result_final = result_final.to(x.dtype)
    tl.store(output_ptr + offsets, result_final, mask=mask)


@triton.jit
def polygamma_n2_kernel(
    x_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for polygamma(n=2) = tetragamma"""
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    # For tetragamma: psi''(x) = -2 * sum(1/(x+k)^3)
    # Use reflection: psi''(x) = psi''(1-x) - 2*pi^3*cos(pi*x)/sin^3(pi*x)
    # For simplicity, skip reflection for x < 0.5

    pi = 3.1415926535897932384626433832795028841971
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Use recurrence: psi''(x+1) = psi''(x) + 2/x^3
    result = tl.zeros_like(x_f32)
    y = xr

    for _ in range(8):
        m = y < 8.0
        result = result + tl.where(m, 2.0 / (y * y * y), 0.0)
        y = tl.where(m, y + 1.0, y)

    # Asymptotic: psi''(x) ~ -2/x^3
    r = 1.0 / y
    r3 = r * r * r
    psi_y = -2.0 * r3

    # Reflection: psi''(x) = psi''(1-x) - 2*pi^3*cos(pi*x)/sin^3(pi*x)
    cos_term = tl.cos(pi * x_f32)
    sin_term = tl.sin(pi * x_f32)
    reflect_term = -2.0 * pi * pi * pi * cos_term / (sin_term * sin_term * sin_term)
    result_final = tl.where(reflect_mask, psi_y + reflect_term, psi_y)

    result_final = result_final.to(x.dtype)
    tl.store(output_ptr + offsets, result_final, mask=mask)


def polygamma(n, x):
    """Compute the n-th derivative of the digamma function."""
    logger.debug("GEMS POLYGAMMA")

    if not isinstance(x, torch.Tensor):
        raise TypeError("polygamma expects a torch.Tensor as the second argument")

    n_elements = x.numel()
    if n_elements == 0:
        return torch.empty_like(x)

    # Allocate output
    output = torch.empty_like(x)

    # Handle non-contiguous tensors
    if not x.is_contiguous():
        x = x.contiguous()

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    # Dispatch to the appropriate kernel based on n
    if n == 0:
        polygamma_digamma_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)
    elif n == 1:
        polygamma_trigamma_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)
    elif n == 2:
        polygamma_n2_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)
    else:
        # For n > 2, fall back to a more general implementation
        raise NotImplementedError(f"polygamma with n={n} not implemented, only n=0,1,2 supported")

    return output