# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)


UNROLL: tl.constexpr = 4  # philox generate 128 random bits at a time


@triton.jit(do_not_specialize=["lower", "upper"])
def rrelu_with_noise_kernel(
    input_ptr,
    noise_ptr,
    output_ptr,
    n_elements,
    lower,
    upper,
    training,
    philox_seed,
    philox_offset,
    BLOCK_SIZE: tl.constexpr,
):
    # Calculate offsets for this program
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE * UNROLL

    # Load input values (4 elements per iteration for UNROLL)
    off_0 = block_start + tl.arange(0, BLOCK_SIZE)
    off_1 = off_0 + BLOCK_SIZE
    off_2 = off_1 + BLOCK_SIZE
    off_3 = off_2 + BLOCK_SIZE

    mask0 = off_0 < n_elements
    mask1 = off_1 < n_elements
    mask2 = off_2 < n_elements
    mask3 = off_3 < n_elements

    x0 = tl.load(input_ptr + off_0, mask=mask0, other=0.0, eviction_policy="evict_first")
    x1 = tl.load(input_ptr + off_1, mask=mask1, other=0.0, eviction_policy="evict_first")
    x2 = tl.load(input_ptr + off_2, mask=mask2, other=0.0, eviction_policy="evict_first")
    x3 = tl.load(input_ptr + off_3, mask=mask3, other=0.0, eviction_policy="evict_first")

    # Convert to float32
    x0_f32 = x0.to(tl.float32)
    x1_f32 = x1.to(tl.float32)
    x2_f32 = x2.to(tl.float32)
    x3_f32 = x3.to(tl.float32)

    # Compute slope
    slope = (lower + upper) * 0.5

    if training:
        # Generate random values using philox
        c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
        i4 = block_start + tl.arange(0, BLOCK_SIZE)
        c0 += i4
        _O = c0 * 0
        r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)

        # Convert to uniform float in [lower, upper]
        r0 = uint_to_uniform_float(r0) * (upper - lower) + lower
        r1 = uint_to_uniform_float(r1) * (upper - lower) + lower
        r2 = uint_to_uniform_float(r2) * (upper - lower) + lower
        r3 = uint_to_uniform_float(r3) * (upper - lower) + lower

        # Apply RReLU: for negative values, multiply by random slope
        # For non-negative values, keep as is
        out0 = tl.where(x0_f32 < 0.0, x0_f32 * r0, x0_f32)
        out1 = tl.where(x1_f32 < 0.0, x1_f32 * r1, x1_f32)
        out2 = tl.where(x2_f32 < 0.0, x2_f32 * r2, x2_f32)
        out3 = tl.where(x3_f32 < 0.0, x3_f32 * r3, x3_f32)

        # Store random values to noise tensor
        tl.store(noise_ptr + off_0, r0, mask=mask0, eviction_policy="evict_first")
        tl.store(noise_ptr + off_1, r1, mask=mask1, eviction_policy="evict_first")
        tl.store(noise_ptr + off_2, r2, mask=mask2, eviction_policy="evict_first")
        tl.store(noise_ptr + off_3, r3, mask=mask3, eviction_policy="evict_first")
    else:
        # Eval mode: use fixed slope
        out0 = tl.where(x0_f32 < 0.0, x0_f32 * slope, x0_f32)
        out1 = tl.where(x1_f32 < 0.0, x1_f32 * slope, x1_f32)
        out2 = tl.where(x2_f32 < 0.0, x2_f32 * slope, x2_f32)
        out3 = tl.where(x3_f32 < 0.0, x3_f32 * slope, x3_f32)

        # Store zeros in noise tensor for eval mode
        zero = tl.full((BLOCK_SIZE,), 0.0, tl.float32)
        tl.store(noise_ptr + off_0, zero, mask=mask0, eviction_policy="evict_first")
        tl.store(noise_ptr + off_1, zero, mask=mask1, eviction_policy="evict_first")
        tl.store(noise_ptr + off_2, zero, mask=mask2, eviction_policy="evict_first")
        tl.store(noise_ptr + off_3, zero, mask=mask3, eviction_policy="evict_first")

    # Convert back to original dtype and store
    tl.store(output_ptr + off_0, out0.to(x0.dtype), mask=mask0, eviction_policy="evict_first")
    tl.store(output_ptr + off_1, out1.to(x1.dtype), mask=mask1, eviction_policy="evict_first")
    tl.store(output_ptr + off_2, out2.to(x2.dtype), mask=mask2, eviction_policy="evict_first")
    tl.store(output_ptr + off_3, out3.to(x3.dtype), mask=mask3, eviction_policy="evict_first")


def _launch_rrelu_with_noise(
    input: torch.Tensor,
    noise: torch.Tensor,
    lower: float,
    upper: float,
    training: bool,
    out: torch.Tensor,
):
    input = input.contiguous()
    noise = noise.contiguous()
    out_t = out.contiguous()

    n_elements = out_t.numel()
    grid_fn = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"] * UNROLL),)
    with torch_device_fn.device(input.device):
        if training:
            philox_seed, philox_offset = philox_backend_seed_offset(
                triton.cdiv(n_elements, UNROLL)
            )
            rrelu_with_noise_kernel[grid_fn](
                input,
                noise,
                out_t,
                n_elements,
                float(lower),
                float(upper),
                1 if training else 0,
                philox_seed,
                philox_offset,
                BLOCK_SIZE=1024,
            )
        else:
            rrelu_with_noise_kernel[grid_fn](
                input,
                noise,
                out_t,
                n_elements,
                float(lower),
                float(upper),
                0,
                0,
                0,
                BLOCK_SIZE=1024,
            )
    if out is not out_t:
        out.copy_(out_t)
    return out


def rrelu_with_noise(
    self: torch.Tensor,
    noise: torch.Tensor,
    lower: float = 0.125,
    upper: float = 0.3333333333333333,
    training: bool = False,
    generator: torch.Generator = None,
):
    logger.debug("GEMS RRELU_WITH_NOISE")
    # Note: generator is ignored for now as in the original implementation
    if self.numel() == 0:
        output = torch.empty_like(self)
        noise.zero_()
        return output

    output = torch.empty_like(self)
    return _launch_rrelu_with_noise(self, noise, lower, upper, training, output)


def rrelu_with_noise_(
    self: torch.Tensor,
    noise: torch.Tensor,
    lower: float = 0.125,
    upper: float = 0.3333333333333333,
    training: bool = False,
    generator: torch.Generator = None,
):
    logger.debug("GEMS RRELU_WITH_NOISE_")
    # Note: generator is ignored for now as in the original implementation
    if self.numel() == 0:
        noise.zero_()
        return self

    return _launch_rrelu_with_noise(self, noise, lower, upper, training, self)