# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)


# Define different block sizes for different tensor sizes
def _get_block_size(n_elements):
    if n_elements < 512:
        return 256
    elif n_elements < 4096:
        return 512
    elif n_elements < 65536:
        return 1024
    else:
        return 2048


@triton.jit
def rrelu_with_noise_forward_kernel(
    x_ptr,
    noise_ptr,
    n_elements,
    lower,
    upper,
    training,
    philox_seed,
    philox_offset,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # Generate random slope for each element
    seed = philox_seed.to(tl.int64)
    offset = philox_offset.to(tl.int64)
    c0 = (offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
    i4 = offsets
    c0 += i4
    _O = c0 * 0
    r0, _, _, _ = tl.philox(seed, c0, c1, _O, _O)
    r = uint_to_uniform_float(r0)

    # Random slope between lower and upper
    random_slope = lower + r * (upper - lower)

    # Fixed slope (average of lower and upper) for eval mode
    fixed_slope = (lower + upper) * 0.5

    # Choose slope based on training mode
    # training is 1 when True, 0 when False
    slope = tl.where(training != 0, random_slope, fixed_slope)

    # Apply RReLU: if x < 0, multiply by slope; else keep as is
    # Also store slope in noise tensor for backward
    output = tl.where(x_f32 < 0, x_f32 * slope, x_f32)
    noise_output = tl.where(x_f32 < 0, slope, x_f32)

    # Cast back to original dtype
    output = output.to(x.dtype)
    noise_output = noise_output.to(x.dtype)

    tl.store(x_ptr + offsets, output, mask=mask)
    tl.store(noise_ptr + offsets, noise_output, mask=mask)


def rrelu_with_noise_(
    input: torch.Tensor,
    noise: torch.Tensor,
    lower: float = 0.125,
    upper: float = 1.0 / 3.0,
    training: bool = False,
    generator: torch.Generator = None,
) -> torch.Tensor:
    logger.debug("GEMS RRELU_WITH_NOISE_")
    if not isinstance(input, torch.Tensor):
        raise TypeError("rrelu_with_noise_ expects a torch.Tensor.")
    if input.is_complex():
        raise TypeError("rrelu_with_noise_ is not supported for complex tensors.")
    if not input.is_contiguous():
        raise ValueError(
            "rrelu_with_noise_ Triton kernel currently supports only contiguous tensors."
        )

    # Ensure noise has same shape as input
    if noise.shape != input.shape:
        raise ValueError(
            f"noise tensor must have the same shape as input: {input.shape} vs {noise.shape}"
        )

    n_elements = input.numel()
    if n_elements == 0:
        return input

    device = input.device

    # Get random seed and offset
    block_size = _get_block_size(n_elements)
    increment = triton.cdiv(n_elements, block_size)
    philox_seed, philox_offset = philox_backend_seed_offset(increment, generator)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(device):
        rrelu_with_noise_forward_kernel[grid](
            input,
            noise,
            n_elements,
            float(lower),
            float(upper),
            1 if training else 0,
            philox_seed,
            philox_offset,
            BLOCK_SIZE=block_size,
        )
    return input


# Also implement the functional version rrelu_with_noise
def rrelu_with_noise(
    input: torch.Tensor,
    noise: torch.Tensor,
    lower: float = 0.125,
    upper: float = 1.0 / 3.0,
    training: bool = False,
    generator: torch.Generator = None,
) -> torch.Tensor:
    logger.debug("GEMS RRELU_WITH_NOISE")
    output = input.clone()
    noise_output = torch.empty_like(noise)
    rrelu_with_noise_(
        output, noise_output, lower=lower, upper=upper, training=training, generator=generator
    )
    return output