# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def scaled_modified_bessel_k1_kernel(
    x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # Handle x <= 0: return inf for x=0, handle negative values
    # K_1 is not defined for x <= 0, but we'll handle the singularity at x=0
    zero = 0.0
    ax = tl.abs(x_f32)
    is_zero = ax < 1e-30  # close to zero
    is_negative = x_f32 < zero

    # For scaled K1: scaled_K1(x) = exp(x) * x * K_1(x)
    # Using polynomial approximation from Cephes/scipy

    # Small region: 0 < x <= 2.0
    # Use series expansion for small x
    t_small = x_f32 * x_f32
    # Polynomial coefficients for small x (approximating x*K1(x)*exp(x))
    # Based on numerical approximation
    p_small = (
        -0.5
        + t_small
        * (
            -0.625
            + t_small
            * (
                0.2916666666666667
                + t_small
                * (
                    -0.06875
                    + t_small * (0.008680555555555555 + t_small * -0.0003854166666666667)
                )
            )
        )
    )
    # Add the leading 1/x term that's part of K1(x) expansion
    # The full expansion for small x: x*K1(x)*exp(x) = 1 + (-0.5)*x^2 + ...
    small_result = 1.0 + p_small

    # For large region: x > 2.0
    # Use asymptotic expansion: K1(x) ~ sqrt(pi/2x) * exp(-x)
    # scaled_K1(x) = exp(x) * x * K1(x) ~ exp(x) * x * sqrt(pi/2x) * exp(-x)
    #              ~ sqrt(pi/2) * sqrt(x)
    y = 2.0 / ax
    p_big = (
        1.2533141373155
        + y
        * (
            -0.0783232033301
            + y
            * (
                0.0218950680508
                + y
                * (
                    -0.0030107026380
                    + y * (0.0003240681134 + y * -0.0001273162979)
                )
            )
        )
    )
    # scaled K1 ~ sqrt(pi/2) * sqrt(x) * (1 + ...)
    big_result = p_big * tl.sqrt(ax)

    # Combine results
    use_small = ax <= 2.0
    result = tl.where(use_small, small_result, big_result)

    # Handle singularity at x=0 -> infinity
    # Handle negative inputs: return inf (following scipy behavior)
    result = tl.where(is_zero, float("inf"), result)
    result = tl.where(is_negative, float("inf"), result)

    # Store result
    tl.store(out_ptr + offsets, result, mask=mask)


def _launch_scaled_modified_bessel_k1(out: torch.Tensor, x: torch.Tensor):
    assert x.is_cuda and out.is_cuda, "Input and output must be CUDA tensors"
    assert (
        out.numel() == x.numel()
    ), "Input and output must have the same number of elements"
    assert out.device == x.device, "Input and output must be on the same device"

    x_in = x
    out_in = out

    # Ensure floating point compute
    if not x_in.is_floating_point():
        x_in = x_in.to(torch.get_default_dtype())

    # Cast input to match the desired output dtype if needed
    if x_in.dtype != out_in.dtype:
        x_in = x_in.to(out_in.dtype)

    x_contig = x_in.contiguous()
    out_was_noncontig = not out_in.is_contiguous()
    out_contig = out_in.contiguous() if out_was_noncontig else out_in

    n_elements = out_contig.numel()
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    scaled_modified_bessel_k1_kernel[grid](
        x_contig, out_contig, n_elements, BLOCK_SIZE=BLOCK_SIZE
    )

    if out_was_noncontig:
        out_in.copy_(out_contig)
    return out_in


def scaled_modified_bessel_k1(x: torch.Tensor):
    logger.debug("GEMS SCALED_MODIFIED_BESSEL_K1")
    if not x.is_cuda:
        raise ValueError(
            "scaled_modified_bessel_k1: input tensor must be on CUDA device"
        )
    # Result dtype follows PyTorch's floating type behavior
    out_dtype = x.dtype if x.is_floating_point() else torch.get_default_dtype()
    out = torch.empty_like(x.to(dtype=out_dtype), dtype=out_dtype, device=x.device)
    _launch_scaled_modified_bessel_k1(out, x)
    return out


def scaled_modified_bessel_k1_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS SCALED_MODIFIED_BESSEL_K1_OUT")
    if not (x.is_cuda and out.is_cuda):
        raise ValueError(
            "scaled_modified_bessel_k1_out: input and output tensors must be on CUDA device"
        )
    if not out.is_floating_point():
        raise TypeError(
            "scaled_modified_bessel_k1_out: output tensor must be a floating point type"
        )
    if x.numel() != out.numel():
        raise ValueError(
            "scaled_modified_bessel_k1_out: input and output must have the same number of elements"
        )
    _launch_scaled_modified_bessel_k1(out, x)
    return out