# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

# Get lgamma from tl_extra_shim for cross-backend compatibility
_lgamma = tl_extra_shim.lgamma


@triton.jit
def _multigammaln_kernel(
    x_ptr, out_ptr, n_elements, p, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # Compute the constant term: C = log(π) * p * (p - 1) / 4
    # Use precomputed log(π) for efficiency
    LOG_PI = 1.1447298858494002  # log(π) precomputed
    # p is a constexpr here, use it directly in float arithmetic
    p_f32: tl.float32 = p
    C = LOG_PI * p_f32 * (p_f32 - 1.0) / 4.0

    # Initialize result as a tensor with the constant C broadcasted
    result = tl.full([BLOCK_SIZE], C, tl.float32)

    # Sum over i from 0 to p-1: lgamma(a - i/2)
    # i = 0, 1, 2, ..., p-1
    # term = a - i/2
    for i in range(p):
        i_f32: tl.float32 = i
        term = x_f32 - i_f32 / 2.0
        result = result + _lgamma(term)

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_special_multigammaln(x: torch.Tensor, out: torch.Tensor, p: int):
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert (
        x.numel() == out.numel()
    ), "Input and output must have the same number of elements"
    assert x.dtype == out.dtype, "Input and output must have the same dtype"

    n_elements = x.numel()
    if n_elements == 0:
        return

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        _multigammaln_kernel[grid](x, out, n_elements, p, BLOCK_SIZE=BLOCK_SIZE)


def special_multigammaln(self: torch.Tensor, p: int):
    logger.debug("GEMS SPECIAL_MULTIGAMMALN")
    x = self
    x_c = x.contiguous()
    out = torch.empty_like(x_c)
    _launch_special_multigammaln(x_c, out, p)
    if x.layout == torch.strided and x.is_contiguous():
        return out
    else:
        return out.view_as(x)


def special_multigammaln_out(self: torch.Tensor, p: int, out: torch.Tensor):
    logger.debug("GEMS SPECIAL_MULTIGAMMALN_OUT")
    x = self
    if out.dtype != x.dtype:
        raise TypeError("out dtype must match input dtype")
    if out.device != x.device:
        raise TypeError("out device must match input device")

    x_c = x.contiguous()
    out_c = out.contiguous()
    _launch_special_multigammaln(x_c, out_c, p)
    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out