# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

# Maximum iteration count for Hermite polynomial computation
# This handles typical use cases where n is small (e.g., n <= 100)
# For larger n, the computation becomes numerically intensive
MAX_HERMITE_ITER = 100


@triton.jit
def hermite_polynomial_h_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements,
    MAX_ITER: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n = tl.load(n_ptr + offsets, mask=mask, other=0).to(tl.int32)

    # Compute in fp32 for better accuracy
    x_f32 = x.to(tl.float32)

    # Compute Hermite polynomial H_n(x) using recurrence:
    # H_0(x) = 1
    # H_1(x) = 2*x
    # H_n(x) = 2*x*H_{n-1}(x) - 2*(n-1)*H_{n-2}(x)

    # Initialize for n=0 and n=1
    h_prev_prev = 1.0 + tl.zeros_like(x_f32)  # H_0 = 1
    h_prev = 2.0 * x_f32  # H_1 = 2*x

    # For n <= 1, handle directly
    # For n >= 2, use recurrence
    # We iterate from 2 to n using a for loop

    # Use a for loop approach with fixed max iterations
    for i in range(2, MAX_ITER):
        # Only update elements that still need iteration (i <= n)
        current_needs_iter = (i <= n) & (n >= 2)

        # Compute H_i = 2*x*H_{i-1} - 2*(i-1)*H_{i-2}
        two_i_minus_2 = (2 * (i - 1)).to(tl.float32)
        h_curr = tl.where(
            current_needs_iter,
            2.0 * x_f32 * h_prev - two_i_minus_2 * h_prev_prev,
            h_prev,
        )

        # Update for next iteration
        h_prev_prev = tl.where(current_needs_iter, h_prev, h_prev_prev)
        h_prev = tl.where(current_needs_iter, h_curr, h_prev)

    # Final result: h_prev holds H_n(x)
    # For n=0: result should be H_0 = 1
    # For n=1: result should be H_1 = 2*x
    # For n >= 2: result is in h_prev

    result = tl.where(
        n == 0,
        1.0 + tl.zeros_like(x_f32),  # H_0 = 1
        tl.where(n == 1, 2.0 * x_f32, h_prev),  # H_1 = 2*x, H_n for n >= 2 is in h_prev
    )

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_hermite_polynomial_h_kernel(
    x: torch.Tensor, n: torch.Tensor, out: torch.Tensor
):
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert x.numel() == n.numel(), "x and n must have the same number of elements"
    assert x.numel() == out.numel(), "Input and output must have the same number of elements"
    assert x.shape == n.shape, "x and n must have the same shape"
    assert x.dtype == out.dtype, "Input and output must have the same dtype"

    n_elements = x.numel()
    if n_elements == 0:
        return out

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        hermite_polynomial_h_kernel[grid](
            x, n, out, n_elements, MAX_HERMITE_ITER, BLOCK_SIZE=BLOCK_SIZE
        )

    return out


def special_hermite_polynomial_h(x: torch.Tensor, n: torch.Tensor):
    """
    ATen wrapper: special_hermite_polynomial_h(Tensor x, Tensor n) -> Tensor

    Computes the physicist's Hermite polynomial H_n(x).

    The Hermite polynomial is defined as:
    - H_0(x) = 1
    - H_1(x) = 2*x
    - H_n(x) = 2*x*H_{n-1}(x) - 2*(n-1)*H_{n-2}(x)
    """
    logger.debug("GEMS SPECIAL_HERMITE_POLYNOMIAL_H")
    x_c = x.contiguous()
    n_c = n.contiguous()
    out = torch.empty_like(x_c)
    _launch_hermite_polynomial_h_kernel(x_c, n_c, out)
    if x.layout == torch.strided and x.is_contiguous():
        return out
    else:
        return out.view_as(x)