# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)

_acos = tl_extra_shim.acos
_sin = tl_extra_shim.sin
_cos = tl_extra_shim.cos


@pointwise_dynamic(promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def chebyshev_polynomial_w_func(x, n):
    # Chebyshev polynomial of the fourth kind W_n(x)
    # Using the trigonometric definition:
    # W_n(cos(theta)) = (sin((n+1)*theta) + sin(n*theta)) / sin(theta)
    # where theta = arccos(x)

    x_f32 = x.to(tl.float32)
    n_f32 = n.to(tl.float32)

    # Handle edge case: |x| > 1 (outside domain of arccos)
    # Clamp x to [-1, 1] to avoid NaN from acos
    x_clamped = tl.where(x_f32 > 1.0, 1.0, x_f32)
    x_clamped = tl.where(x_f32 < -1.0, -1.0, x_clamped)

    theta = _acos(x_clamped)
    sin_theta = _sin(theta)

    # Avoid division by zero
    sin_theta = tl.where(tl.abs(sin_theta) < 1e-10, 1e-10, sin_theta)

    # Compute W_n(x) = (sin((n+1)*theta) + sin(n*theta)) / sin(theta)
    numerator = _sin((n_f32 + 1.0) * theta) + _sin(n_f32 * theta)
    result = numerator / sin_theta

    return result


def chebyshev_polynomial_w(x, n):
    logger.debug("GEMS CHEBYSHEV_POLYNOMIAL_W")
    # Convert scalar n to tensor if needed
    if not isinstance(n, torch.Tensor):
        n = torch.tensor(n, dtype=torch.int64, device=x.device)
    return chebyshev_polynomial_w_func(x, n)