import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def special_zeta_kernel(x, q):
    """
    Compute the Hurwitz zeta function: ζ(x, q) = Σ_{k=0}^∞ 1/(k+q)^x
    Using the identity: 1/(k+q)^x = exp(-x * log(k+q))
    """
    # Use to() to convert to float32 as in exp.py
    x_f32 = x.to(tl.float32)
    q_f32 = q.to(tl.float32)
    neg_x = -x_f32

    # Compute first term: 1/q^x = exp(-x * log(q))
    log_q = tl.math.log(q_f32)
    result = tl.exp(neg_x * log_q)

    # Add remaining terms (manually unrolled for more accuracy)
    result = result + tl.exp(neg_x * tl.math.log(1.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(2.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(3.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(4.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(5.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(6.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(7.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(8.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(9.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(10.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(11.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(12.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(13.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(14.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(15.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(16.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(17.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(18.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(19.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(20.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(21.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(22.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(23.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(24.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(25.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(26.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(27.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(28.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(29.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(30.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(31.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(32.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(33.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(34.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(35.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(36.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(37.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(38.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(39.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(40.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(41.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(42.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(43.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(44.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(45.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(46.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(47.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(48.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(49.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(50.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(51.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(52.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(53.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(54.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(55.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(56.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(57.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(58.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(59.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(60.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(61.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(62.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(63.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(64.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(65.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(66.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(67.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(68.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(69.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(70.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(71.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(72.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(73.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(74.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(75.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(76.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(77.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(78.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(79.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(80.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(81.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(82.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(83.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(84.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(85.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(86.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(87.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(88.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(89.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(90.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(91.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(92.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(93.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(94.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(95.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(96.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(97.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(98.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(99.0 + q_f32))

    # Convert back to input dtype
    result = result.to(x.dtype)

    return result


# For scalar-tensor case
@pointwise_dynamic(is_tensor=[False, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def special_zeta_kernel_scalar_tensor(x, q):
    x_f32 = x.to(tl.float32)
    q_f32 = q.to(tl.float32)
    neg_x = -x_f32
    log_q = tl.math.log(q_f32)
    result = tl.exp(neg_x * log_q)
    result = result + tl.exp(neg_x * tl.math.log(1.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(2.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(3.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(4.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(5.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(6.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(7.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(8.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(9.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(10.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(11.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(12.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(13.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(14.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(15.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(16.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(17.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(18.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(19.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(20.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(21.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(22.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(23.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(24.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(25.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(26.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(27.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(28.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(29.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(30.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(31.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(32.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(33.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(34.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(35.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(36.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(37.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(38.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(39.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(40.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(41.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(42.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(43.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(44.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(45.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(46.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(47.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(48.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(49.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(50.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(51.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(52.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(53.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(54.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(55.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(56.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(57.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(58.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(59.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(60.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(61.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(62.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(63.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(64.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(65.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(66.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(67.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(68.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(69.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(70.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(71.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(72.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(73.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(74.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(75.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(76.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(77.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(78.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(79.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(80.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(81.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(82.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(83.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(84.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(85.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(86.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(87.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(88.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(89.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(90.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(91.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(92.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(93.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(94.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(95.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(96.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(97.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(98.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(99.0 + q_f32))
    result = result.to(q.dtype)
    return result


# For tensor-scalar case
@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def special_zeta_kernel_tensor_scalar(x, q):
    x_f32 = x.to(tl.float32)
    q_f32 = q.to(tl.float32)
    neg_x = -x_f32
    log_q = tl.math.log(q_f32)
    result = tl.exp(neg_x * log_q)
    result = result + tl.exp(neg_x * tl.math.log(1.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(2.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(3.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(4.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(5.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(6.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(7.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(8.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(9.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(10.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(11.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(12.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(13.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(14.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(15.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(16.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(17.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(18.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(19.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(20.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(21.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(22.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(23.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(24.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(25.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(26.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(27.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(28.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(29.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(30.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(31.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(32.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(33.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(34.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(35.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(36.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(37.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(38.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(39.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(40.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(41.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(42.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(43.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(44.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(45.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(46.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(47.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(48.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(49.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(50.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(51.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(52.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(53.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(54.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(55.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(56.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(57.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(58.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(59.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(60.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(61.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(62.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(63.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(64.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(65.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(66.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(67.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(68.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(69.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(70.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(71.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(72.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(73.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(74.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(75.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(76.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(77.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(78.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(79.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(80.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(81.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(82.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(83.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(84.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(85.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(86.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(87.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(88.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(89.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(90.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(91.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(92.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(93.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(94.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(95.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(96.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(97.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(98.0 + q_f32))
    result = result + tl.exp(neg_x * tl.math.log(99.0 + q_f32))
    result = result.to(x.dtype)
    return result


def special_zeta(A, B):
    """
    Compute the Hurwitz zeta function elementwise.
    ζ(x, q) = Σ_{k=0}^∞ 1/(k+q)^x
    """
    logger.debug("GEMS SPECIAL_ZETA")
    if isinstance(A, torch.Tensor) and isinstance(B, torch.Tensor):
        return special_zeta_kernel(A, B)
    elif isinstance(A, torch.Tensor):
        return special_zeta_kernel_tensor_scalar(A, B)
    elif isinstance(B, torch.Tensor):
        return special_zeta_kernel_scalar_tensor(A, B)
    else:
        result = sum(1.0 / (k + B) ** A for k in range(100))
        return torch.tensor(result, dtype=torch.float32)


def special_zeta_(A, B):
    raise NotImplementedError("In-place special_zeta is not supported")