# Generated by FlagGems
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.digamma_ import digamma_
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

_pow = tl_extra_shim.pow


@triton.jit
def trigamma_kernel(
    x_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    pi = 3.1415926535897932384626433832795028841971

    # psi'(x) = sum_{k=0}^inf 1/(x+k)^2
    # Use reflection for x < 0.5: psi'(x) = psi'(1-x) + pi^2/sin^2(pi*x)
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Shift to large values using recurrence: psi'(x+1) = psi'(x) - 1/x^2
    shift = tl.zeros_like(x_f32)
    y = xr
    for _ in range(12):
        m = y < 12.0
        term = tl.where(m, 1.0 / (y * y), 0.0)
        shift = shift - term
        y = tl.where(m, y + 1.0, y)

    # Asymptotic expansion: psi'(y) ~ 1/y + 1/(2*y^2) + 1/(6*y^3) - 1/(30*y^5) + ...
    r = 1.0 / y
    r2 = r * r
    r3 = r2 * r
    r4 = r3 * r
    r5 = r4 * r
    r6 = r5 * r
    r7 = r6 * r

    # Asymptotic series with more terms
    series_sum = r + 0.5 * r2 + (1.0 / 6.0) * r3 - (1.0 / 30.0) * r5 + (1.0 / 42.0) * r6 - (1.0 / 30.0) * r7

    result = series_sum + shift

    # Apply reflection
    sin_term = tl.sin(pi * x_f32)
    reflection_add = pi * pi / (sin_term * sin_term)
    result = tl.where(reflect_mask, result + reflection_add, result)

    result = result.to(x.dtype)
    tl.store(output_ptr + offsets, result, mask=mask)


@triton.jit
def polygamma_n2_kernel(
    x_ptr,
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    pi = 3.1415926535897932384626433832795028841971

    # psi''(x) = -2 * sum_{k=0}^inf 1/(x+k)^3
    reflect_mask = x_f32 < 0.5
    xr = tl.where(reflect_mask, 1.0 - x_f32, x_f32)

    # Shift using recurrence: psi''(x+1) = psi''(x) + 2/x^3
    shift = tl.zeros_like(x_f32)
    y = xr
    for _ in range(12):
        m = y < 12.0
        term = tl.where(m, 2.0 / (y * y * y), 0.0)
        shift = shift + term
        y = tl.where(m, y + 1.0, y)

    # Asymptotic expansion for psi''
    r = 1.0 / y
    r2 = r * r
    r3 = r2 * r
    r4 = r3 * r
    r5 = r4 * r
    r6 = r5 * r
    r7 = r6 * r
    r8 = r7 * r

    series_sum = r2 + r3 + 0.5 * r4 + (1.0 / 3.0) * r5 + (1.0 / 6.0) * r6 - (1.0 / 12.0) * r7 + (1.0 / 6.0) * r8

    # sign is (-1)^(n+1) = (-1)^3 = -1, so multiply by -2
    result = -2.0 * (series_sum + shift)

    # Reflection: psi''(1-x) + psi''(x) = 2*pi^3 * cos(pi*x) / sin^3(pi*x)
    cos_term = tl.cos(pi * x_f32)
    sin_term = tl.sin(pi * x_f32)
    reflection_add = 2.0 * pi * pi * pi * cos_term / (sin_term * sin_term * sin_term)
    result = tl.where(reflect_mask, result + reflection_add, result)

    result = result.to(x.dtype)
    tl.store(output_ptr + offsets, result, mask=mask)


def special_polygamma(n, x):
    logger.debug("GEMS SPECIAL_POLYGAMMA")
    if not isinstance(x, torch.Tensor):
        raise TypeError("special_polygamma expects a torch.Tensor as input")

    # Handle n as tensor or int
    if isinstance(n, torch.Tensor):
        n = n.item()

    n = int(n)
    if n < 0:
        raise ValueError("polygamma order n must be >= 0")

    # Allocate output
    output = torch.empty_like(x)

    # Handle non-contiguous tensors
    if not x.is_contiguous():
        x = x.contiguous()
    if not output.is_contiguous():
        output = output.contiguous()

    n_elements = x.numel()
    if n_elements == 0:
        return output

    if n == 0:
        # Use the existing digamma implementation
        # Digamma works in-place, so we need to copy input
        temp = x.float().to(x.device)
        result = digamma_(temp)
        output.copy_(result.to(x.dtype))
    elif n == 1:
        # Trigamma
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(x.device):
            trigamma_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)
    elif n == 2:
        # Second polygamma
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(x.device):
            polygamma_n2_kernel[grid](x, output, n_elements, BLOCK_SIZE=1024)
    else:
        # For n > 2, use a general series approximation
        # This is less accurate but handles any n
        # psi^(n)(x) = (-1)^(n+1) * n! * sum_{k=0}^inf 1/(x+k)^(n+1)

        # Pre-compute factorial
        factorial_vals = [1.0, 1.0, 2.0, 6.0, 24.0, 120.0, 720.0, 5040.0, 40320.0]
        factorial_n = factorial_vals[min(n, 8)]

        # Sign = (-1)^(n+1)
        sign = -1.0 if n % 2 == 0 else 1.0

        n_plus_1 = n + 1

        # Direct series sum for moderate x
        x_f32 = x.float()
        series_sum = torch.zeros_like(x_f32)
        y = x_f32
        for k in range(20):
            series_sum = series_sum + _pow(y, -n_plus_1)
            y = y + 1.0

        # Asymptotic correction for the tail
        r = 1.0 / x_f32
        tail_approx = _pow(r, n) / n

        result = sign * factorial_n * (series_sum + tail_approx)
        output.copy_(result.to(x.dtype))

    return output


def special_polygamma_(x, n=0):
    """In-place version"""
    logger.debug("GEMS SPECIAL_POLYGAMMA_")
    if not isinstance(x, torch.Tensor):
        raise TypeError("special_polygamma_ expects a torch.Tensor as input")

    result = special_polygamma(n, x)
    x.copy_(result)
    return x