# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _chebyshev_u_kernel(x_ptr, n_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    """Kernel for computing Chebyshev polynomial U_n(x)."""
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n = tl.load(n_ptr + offsets, mask=mask, other=0)

    # Convert to float32 for computation
    xf = x.to(tl.float32)

    # Compute Chebyshev polynomial U_n(x) for each element
    # U_0(x) = 1
    # U_1(x) = 2x
    # U_n(x) = 2*x*U_{n-1}(x) - U_{n-2}(x)

    # Initialize U_-1 and U_0 for recurrence
    # Using U_-1 = 0 gives U_1 = 2*x*U_0 - U_-1 = 2*x*1 - 0 = 2*x
    u_m1 = tl.cast(0.0, tl.float32)  # U_-1 = 0
    u_0 = tl.cast(1.0, tl.float32)   # U_0 = 1

    # Compute and store results for each n value
    # Start with n=0: result = U_0 = 1
    result = u_0

    # n=1: U_1 = 2*x*U_0 - U_-1 = 2*x*1 - 0 = 2*x
    u_1 = 2.0 * xf * u_0 - u_m1
    result = tl.where(n == 1, u_1, result)

    # n=2: U_2 = 2*x*U_1 - U_0
    u_2 = 2.0 * xf * u_1 - u_0
    result = tl.where(n == 2, u_2, result)

    # n=3: U_3 = 2*x*U_2 - U_1
    u_3 = 2.0 * xf * u_2 - u_1
    result = tl.where(n == 3, u_3, result)

    # n=4: U_4 = 2*x*U_3 - U_2
    u_4 = 2.0 * xf * u_3 - u_2
    result = tl.where(n == 4, u_4, result)

    # n=5: U_5 = 2*x*U_4 - U_3
    u_5 = 2.0 * xf * u_4 - u_3
    result = tl.where(n == 5, u_5, result)

    # n=6: U_6 = 2*x*U_5 - U_4
    u_6 = 2.0 * xf * u_5 - u_4
    result = tl.where(n == 6, u_6, result)

    # n=7: U_7 = 2*x*U_6 - U_5
    u_7 = 2.0 * xf * u_6 - u_5
    result = tl.where(n == 7, u_7, result)

    # n=8: U_8 = 2*x*U_7 - U_6
    u_8 = 2.0 * xf * u_7 - u_6
    result = tl.where(n == 8, u_8, result)

    # n=9: U_9 = 2*x*U_8 - U_7
    u_9 = 2.0 * xf * u_8 - u_7
    result = tl.where(n == 9, u_9, result)

    # n=10: U_10 = 2*x*U_9 - U_8
    u_10 = 2.0 * xf * u_9 - u_8
    result = tl.where(n == 10, u_10, result)

    # For larger n, use a loop
    # We need to shift the values and continue
    u_m1 = u_10
    u_0 = u_9
    u_1 = u_10

    # Continue for n=11 to n=31 (support n up to 31)
    for i in tl.static_range(11, 32):
        u_next = 2.0 * xf * u_1 - u_0
        result = tl.where(n == i, u_next, result)
        u_m1 = u_0
        u_0 = u_1
        u_1 = u_next

    # Convert back to input dtype
    result = result.to(x.dtype)

    tl.store(out_ptr + offsets, result, mask=mask)


def _run_chebyshev_u_kernel(x: torch.Tensor, n: torch.Tensor, out: torch.Tensor):
    """Run the Chebyshev polynomial kernel."""
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert x.shape == n.shape, "x and n must have the same shape"
    assert x.shape == out.shape, "Input and output must have the same shape"
    assert x.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ), "Unsupported dtype for x"
    assert n.dtype in (
        torch.int32,
        torch.int64,
    ), "Unsupported dtype for n"

    # Broadcast n to match x if needed
    if n.shape != x.shape:
        n = n.expand(x.shape)

    x_c = x.contiguous()
    n_c = n.contiguous()
    out_c = out.contiguous()

    n_elements = out_c.numel()
    if n_elements == 0:
        return out

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    _chebyshev_u_kernel[grid](x_c, n_c, out_c, n_elements, BLOCK_SIZE=1024)

    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out


def special_chebyshev_polynomial_u(x, n):
    """
    Computes the Chebyshev polynomial of the first kind U_n(x).

    Args:
        x: Input tensor (float)
        n: Order of the polynomial (integer tensor, same shape as x)

    Returns:
        The Chebyshev polynomial U_n(x) evaluated at x
    """
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_U")

    # Handle scalar n (n_scalar overload)
    if not isinstance(n, torch.Tensor):
        n = torch.tensor([n], dtype=torch.long, device=x.device)
        # Expand to match x shape if needed
        if x.dim() > 0:
            n = n.expand(x.shape)

    # Create output tensor
    out = torch.empty_like(x)

    return _run_chebyshev_u_kernel(x, n, out)


def special_chebyshev_polynomial_u_(x, n, out: torch.Tensor = None):
    """
    Out variant of special_chebyshev_polynomial_u.

    Args:
        x: Input tensor (float)
        n: Order of the polynomial (integer tensor, same shape as x)
        out: Output tensor (optional)

    Returns:
        The Chebyshev polynomial U_n(x) evaluated at x
    """
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_U_")

    # Handle scalar n
    if not isinstance(n, torch.Tensor):
        n = torch.tensor([n], dtype=torch.long, device=x.device)
        if x.dim() > 0:
            n = n.expand(x.shape)

    # Handle out parameter
    if out is None:
        out = torch.empty_like(x)
    else:
        # Broadcast input to out's shape if needed
        if x.shape != out.shape:
            x = x.expand(out.shape)
        if n.shape != out.shape:
            n = n.expand(out.shape)

    return _run_chebyshev_u_kernel(x, n, out)