# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def transpose_2d_kernel(
    in_ptr,
    out_ptr,
    in_stride_0,
    in_stride_1,
    out_stride_0,
    out_stride_1,
    M,  # input dim0
    N,  # input dim1
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    i = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)  # corresponds to out rows [0..N)
    j = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)  # corresponds to out cols [0..M)

    i64 = i.to(tl.int64)[None, :]  # shape [1, BM]
    j64 = j.to(tl.int64)[:, None]  # shape [BN, 1]

    # out shape = (N, M)
    mask = (i64 < N) & (j64 < M)

    # in index = (j, i) -> in_offset = j*in_stride_0 + i*in_stride_1
    in_offsets = j64 * in_stride_0 + i64 * in_stride_1
    # out index = (i, j) -> out_offset = i*out_stride_0 + j*out_stride_1
    out_offsets = i64 * out_stride_0 + j64 * out_stride_1

    x = tl.load(in_ptr + in_offsets, mask=mask)
    tl.store(out_ptr + out_offsets, x, mask=mask)


@triton.jit
def copy_1d_strided_kernel(
    in_ptr,
    out_ptr,
    in_stride,
    out_stride,
    N,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offs < N
    offs64 = offs.to(tl.int64)
    in_idx = offs64 * in_stride
    out_idx = offs64 * out_stride
    x = tl.load(in_ptr + in_idx, mask=mask)
    tl.store(out_ptr + out_idx, x, mask=mask)


def _launch_transpose_kernel(inp: torch.Tensor, out: torch.Tensor):
    assert inp.is_cuda and out.is_cuda, "transpose kernels require CUDA tensors"
    assert inp.dtype == out.dtype, "dtype mismatch between input and output"

    dim = inp.dim()
    if dim == 0:
        # Scalar copy
        n = 1
        grid = lambda meta: (triton.cdiv(n, meta["BLOCK_SIZE"]),)
        copy_1d_strided_kernel[grid](
            inp,
            out,
            0,
            0,
            n,
            BLOCK_SIZE=1,
        )
    elif dim == 1:
        # 1D tensor - just copy
        n = inp.numel()
        in_stride = inp.stride(0)
        out_stride = out.stride(0)
        grid = lambda meta: (triton.cdiv(n, meta["BLOCK_SIZE"]),)
        copy_1d_strided_kernel[grid](
            inp,
            out,
            in_stride,
            out_stride,
            n,
            BLOCK_SIZE=1024,
        )
    elif dim == 2:
        M, N = inp.shape
        in_s0, in_s1 = inp.stride()
        out_s0, out_s1 = out.stride()
        grid = lambda meta: (
            triton.cdiv(N, meta["BLOCK_M"]),
            triton.cdiv(M, meta["BLOCK_N"]),
        )
        transpose_2d_kernel[grid](
            inp,
            out,
            in_s0,
            in_s1,
            out_s0,
            out_s1,
            M,
            N,
            BLOCK_M=32,
            BLOCK_N=32,
        )
    else:
        raise RuntimeError("transpose expects a tensor with <= 2 dims")


def transpose_out(
    input: torch.Tensor,
    dim0: int,
    dim1: int,
    out: torch.Tensor,
):
    logger.debug("GEMS TRANSPOSE_OUT")
    _launch_transpose_kernel(input, out)
    return out


def transpose(input: torch.Tensor, dim0: int, dim1: int) -> torch.Tensor:
    logger.debug("GEMS TRANSPOSE")
    # Validate dimensions
    dim = input.dim()
    assert (
        dim0 >= -dim and dim0 < dim
    ), "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
        -dim, dim - 1, dim0
    )
    assert (
        dim1 >= -dim and dim1 < dim
    ), "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
        -dim, dim - 1, dim1
    )

    # Normalize negative dimensions
    dim0 = dim0 if dim0 >= 0 else dim0 + dim
    dim1 = dim1 if dim1 >= 0 else dim1 + dim

    # Handle trivial cases
    if dim0 == dim1:
        return input.clone()
    if dim == 0 or dim == 1:
        return input.clone()

    # For general case with > 2 dims, we need to permute the dimensions
    # This is a simplified implementation that only handles 2D case efficiently
    # For higher dimensions, fall back to torch.transpose
    if dim != 2:
        # Use torch.transpose for general case
        # Note: We could implement a more general version but keeping it simple for now
        return torch.transpose(input, dim0, dim1)

    # 2D case: swap dimensions
    M, N = input.shape
    out = torch.empty(
        (N, M),
        dtype=input.dtype,
        device=input.device,
        memory_format=torch.contiguous_format,
    )
    _launch_transpose_kernel(input, out)
    return out


def transpose_(input: torch.Tensor, dim0: int, dim1: int) -> torch.Tensor:
    logger.debug("GEMS TRANSPOSE_")
    # Validate dimensions
    dim = input.dim()
    assert (
        dim0 >= -dim and dim0 < dim
    ), "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
        -dim, dim - 1, dim0
    )
    assert (
        dim1 >= -dim and dim1 < dim
    ), "Dimension out of range (expected to be in range of [{}, {}], but got {})".format(
        -dim, dim - 1, dim1
    )

    # Normalize negative dimensions
    dim0 = dim0 if dim0 >= 0 else dim0 + dim
    dim1 = dim1 if dim1 >= 0 else dim1 + dim

    # Handle trivial cases
    if dim0 == dim1:
        return input
    if dim == 0 or dim == 1:
        return input

    # For general case with > 2 dims, use torch.transpose (in-place is not really possible)
    if dim != 2:
        # For non-2D, we need to clone and assign using view
        temp = torch.transpose(input, dim0, dim1)
        input.view_as(temp).copy_(temp)
        return input

    # 2D case: we need to swap dimensions in-place
    # This is done by creating a new view of the data and copying
    M, N = input.shape
    # Get the original data pointer and dtype
    original_dtype = input.dtype
    device = input.device

    # Perform transpose and copy back
    temp = torch.empty(
        (N, M),
        dtype=original_dtype,
        device=device,
        memory_format=torch.contiguous_format,
    )
    _launch_transpose_kernel(input, temp)

    # Reshape input in-place to match temp's shape
    input.view(N, M).copy_(temp)
    return input