# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _unbind_copy_kernel(
    src_ptr,
    dst_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    vals = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, vals, mask=mask)


def unbind_copy(x: torch.Tensor, dim: int = 0):
    logger.debug("GEMS UNBIND_COPY")
    """
    Wrapper for aten::unbind_copy
    Splits a tensor into a sequence of tensors along the given dimension.
    Unlike unbind, unbind_copy returns fresh copies instead of views.
    """
    if dim < 0:
        dim = x.dim() + dim

    n_elements = x.numel()
    if n_elements == 0:
        return tuple()

    size = x.shape[dim]
    if size == 0:
        return tuple()

    # Get slice shape (all dimensions except the split dim)
    slice_shape = list(x.shape)
    del slice_shape[dim]

    # Create output tensors
    output = []

    # Process each slice individually with contiguous copy
    for i in range(size):
        out = torch.empty(
            slice_shape, dtype=x.dtype, device=x.device, layout=torch.strided
        )

        if out.numel() == 0:
            output.append(out)
            continue

        # Get the i-th slice along dim and make it contiguous
        src_slice = torch.select(x, dim, i).contiguous()
        dst_slice = out

        n_elements_slice = dst_slice.numel()
        if n_elements_slice == 0:
            output.append(out)
            continue

        if not dst_slice.is_contiguous():
            dst_slice = dst_slice.contiguous()

        grid = lambda meta: (triton.cdiv(n_elements_slice, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(x.device):
            _unbind_copy_kernel[grid](
                src_slice, dst_slice, n_elements_slice, BLOCK_SIZE=1024
            )
        output.append(dst_slice)

    return tuple(output)


def unbind_copy_out(x: torch.Tensor, dim: int = 0, out=None):
    logger.debug("GEMS UNBIND_COPY_OUT")
    """
    Wrapper for aten::unbind_copy.out
    Stores results in pre-allocated output tensors.
    """
    if out is not None:
        raise NotImplementedError("unbind_copy_out with pre-allocated output is not implemented")

    return unbind_copy(x, dim)